-- Kreira tabelu za čuvanje istorije fetch-ovanja za svaki flux
CREATE TABLE public."fetchingHistory" (
    "fetchingID" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "fluxID" BIGINT NOT NULL,
    "status" TEXT NOT NULL,
    "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "completedAt" TIMESTAMP WITH TIME ZONE,
    "fetchingTimeInSeconds" INTEGER,
    "progress" INTEGER,
    "numberOfContent" INTEGER,
    "errorMessage" TEXT,
    CONSTRAINT "fetchingHistory_pkey" PRIMARY KEY ("fetchingID")
);

-- Opciono: Dodavanje indeksa za brže pretrage po fluxID
CREATE INDEX "idx_fetchingHistory_fluxID" ON public."fetchingHistory" ("fluxID");

-- Opciono: Dodavanje komentara na tabelu i kolone radi bolje dokumentacije
COMMENT ON TABLE public."fetchingHistory" IS 'Sadrži istoriju svih pokušaja fetch-ovanja podataka za svaki flux.';
COMMENT ON COLUMN public."fetchingHistory"."fetchingID" IS 'Jedinstveni identifikator zapisa o fetch-ovanju.';
COMMENT ON COLUMN public."fetchingHistory"."fluxID" IS 'ID flux-a na koji se ovaj zapis odnosi.';
COMMENT ON COLUMN public."fetchingHistory"."status" IS 'Status procesa fetch-ovanja (npr. "completed", "failed", "in_progress").';
COMMENT ON COLUMN public."fetchingHistory"."timestamp" IS 'Vreme početka procesa fetch-ovanja.';
COMMENT ON COLUMN public."fetchingHistory"."completedAt" IS 'Vreme završetka procesa fetch-ovanja.';
COMMENT ON COLUMN public."fetchingHistory"."fetchingTimeInSeconds" IS 'Ukupno trajanje procesa u sekundama.';
COMMENT ON COLUMN public."fetchingHistory"."progress" IS 'Procenat završenosti procesa (0-100).';
COMMENT ON COLUMN public."fetchingHistory"."numberOfContent" IS 'Broj preuzetih stavki sadržaja.';
COMMENT ON COLUMN public."fetchingHistory"."errorMessage" IS 'Poruka o grešci, ako je do nje došlo.';
